// <auto-generated />
using System;
using EmployerPortal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployerPortal.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220420060604_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployerPortal.API.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agent_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Date_Created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Employed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Of_Birth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Othernames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin_Invalid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scheme_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State_Of_Posting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upload_Date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerCode");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agent_Code = "",
                            Client_Status = "C",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date_Created = "2012-04-01",
                            Date_Employed = "2012-04-01",
                            Date_Of_Birth = "1986-10-26",
                            Email = "sheyions4real@yahoo.co.uk",
                            EmployerCode = "PR0000613584",
                            EmployerName = "OAK PENSIONS LIMITED",
                            Firstname = "Sheyi",
                            Gender = "M",
                            Mobile_Phone = "08134454808",
                            Othernames = "Matthew",
                            Pin = "PEN100599222817",
                            Pin_Invalid = "0",
                            Scheme_Id = "2000006",
                            Ssn = "",
                            State_Of_Posting = "LA",
                            Surname = "Omagene",
                            Title = "Mr",
                            Upload_Date = "2012-04-01"
                        });
                });

            modelBuilder.Entity("EmployerPortal.API.Data.Employer", b =>
                {
                    b.Property<string>("EmployerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Officer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployerCode");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            EmployerCode = "PR0000613584",
                            Address = "15B OKO AWO STREET  VICTORIA ISLAND, LAGOS",
                            City = "LAGOS",
                            Contact_Officer_Name = "Akinwumi A.",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@oakpensions.com",
                            EmployerName = "OAK PENSIONS LIMITED",
                            Id = 1,
                            Industry = "Finance",
                            Mobile_Phone = "07002255625",
                            Sector = "Private",
                            State = "LAGOS"
                        },
                        new
                        {
                            EmployerCode = "PR0000041041",
                            Address = "PLOT 590 ZONE A.O NAIC HOUSE CBD",
                            City = "Abuja",
                            Contact_Officer_Name = "AYEKAME ELUKPO",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            EmployerName = "DUETHEL PRO SERVICES LIMITED",
                            Id = 2,
                            Industry = "Finance",
                            Mobile_Phone = "08126696169",
                            Sector = "Private",
                            State = "FCT"
                        },
                        new
                        {
                            EmployerCode = "PR0000041042",
                            Address = "16 YASHIM DOGARA CRESCENT DAWAKI ABUJA",
                            City = "Abuja",
                            Contact_Officer_Name = "",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            EmployerName = "WINCREST CONSULT LIMITED",
                            Id = 3,
                            Industry = "Finance",
                            Mobile_Phone = "08163313858",
                            Sector = "Private",
                            State = "FCT"
                        });
                });

            modelBuilder.Entity("EmployerPortal.API.Data.EmployerAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployerContact_Officer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerMobile_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Officer_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelationshipManagerID")
                        .HasColumnType("int");

                    b.Property<string>("State_Of_Posting")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerCode");

                    b.HasIndex("RelationshipManagerID");

                    b.ToTable("EmployerAllocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployerAddress = "266 Murtala Muhammed Way, Alagomeji Yaba",
                            EmployerCity = "Lagos",
                            EmployerCode = "PR0000613584",
                            EmployerContact_Officer_Name = "Henry Christopher",
                            EmployerEmail = "info@oakpensions.com",
                            EmployerMobile_Phone = "07002255625",
                            EmployerState = "LA",
                            Officer_Position = "Head, HR",
                            RelationshipManagerID = 1,
                            State_Of_Posting = "LA"
                        });
                });

            modelBuilder.Entity("EmployerPortal.API.Data.NewPaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmationOfPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContributionMonth")
                        .HasColumnType("int");

                    b.Property<int>("ContributionYear")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ScheduleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScheduleFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployerCode");

                    b.ToTable("NewPaymentSchedules");
                });

            modelBuilder.Entity("EmployerPortal.API.Data.RelationshipManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Othernames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfPosting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RelationshipManagers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentCode = "LAG101",
                            BranchCode = "LA",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lolua@oakpensions.com",
                            Firstname = "Omololu",
                            Gender = "M",
                            Mobile_Phone = "08029510718",
                            Othernames = "Olasupo",
                            StateOfPosting = "LA",
                            Surname = "Adetula",
                            Title = "Mr"
                        });
                });

            modelBuilder.Entity("EmployerPortal.API.Data.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<double>("Amount_Processed")
                        .HasColumnType("float");

                    b.Property<bool?>("Checked")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IDNO")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Refund_Amount")
                        .HasColumnType("float");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployerCode");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2021556.46,
                            Amount_Processed = 0.0,
                            Checked = false,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "REM  N-10042361295/PR0000613584/NIP0341903290-000000364600 91004236129",
                            EmployerCode = "PR0000613584",
                            IDNO = 200734,
                            RefNo = "S50268032-2",
                            Refund_Amount = 0.0,
                            StatusCode = "R",
                            ValueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1987)
                        });
                });

            modelBuilder.Entity("EmployerPortal.API.Data.Employee", b =>
                {
                    b.HasOne("EmployerPortal.API.Data.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerCode");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("EmployerPortal.API.Data.EmployerAllocation", b =>
                {
                    b.HasOne("EmployerPortal.API.Data.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerCode");

                    b.HasOne("EmployerPortal.API.Data.RelationshipManager", "RelationshipManager")
                        .WithMany()
                        .HasForeignKey("RelationshipManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("RelationshipManager");
                });

            modelBuilder.Entity("EmployerPortal.API.Data.NewPaymentSchedule", b =>
                {
                    b.HasOne("EmployerPortal.API.Data.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerCode");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("EmployerPortal.API.Data.Schedule", b =>
                {
                    b.HasOne("EmployerPortal.API.Data.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerCode");

                    b.Navigation("Employer");
                });
#pragma warning restore 612, 618
        }
    }
}
